# User config
author: "Elies Delgado Tamarit."

tagline: "This is me."

description: "My name is Elies and I'm an enthusiastic and hard-working youngster from Barcelona who is always ready to embrace new challenges, adventures and opportunities."

description2: "I strongly believe we all have the potential to be creative and innovative, and I aim to prove it."

description3: "I love the magic of connecting and interacting with other individuals, and I am constantly seeking for it."

description4: ""

keywords: "Elies Delgado Tamarit, Music, Festivals, Technology, Innovation, Marketing, Communication, Business, Entrepreneurship"

email: "elies.delgado@example.com"
linkedin: "https://www.linkedin.com/in/eliesdt/"
twitter: "https://twitter.com/thisiselies"
github: "https://github.com/"

baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed